### ISSUE TITLE
String was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by vjmattila** [lukehutton/streamlauncher#22]
Getting the error when retrieving stream list

20150221 193920.332 [9] INFO StreamLauncher.Repositories.HockeyStreamRepository - Retrieved 59 live streams
20150221 193920.332 [1] ERROR StreamLauncher.Wpf.ViewModel.StreamsViewModel - An error occurred while getting live streams.
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at StreamLauncher.Mappers.LiveStreamScheduleAggregatorAndMapper.AggregateAndMap(GetLiveStreamsResponseDto getLiveStreamsResponseDto)
   at StreamLauncher.Repositories.HockeyStreamRepository.GetLiveStreams(DateTime date)
   at StreamLauncher.Wpf.ViewModel.StreamsViewModel.<GetStreams>d__7.MoveNext()

**Comment by lukehutton** [comment]
Thanks @vjmattila I'll take a look
