### ISSUE TITLE
Win8 64bit crash

### ISSUE THREAD

**Issue by lukehutton** [lukehutton/streamlauncher#3]
Log Name:      Application
Source:        .NET Runtime
Date:          2015-01-17 7:23:47 PM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:     
Description:
Application: StreamLauncher.Wpf.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ApplicationException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-01-18T03:23:47.000000000Z" />
    <EventRecordID>9926</EventRecordID>
    <Channel>Application</Channel>
    <Computer></Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: StreamLauncher.Wpf.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ApplicationException
Stack:
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.&lt;ThrowAsync&gt;b__5(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          2015-01-17 7:24:49 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      Jorgs-PC
Description:
Faulting application name: StreamLauncher.Wpf.exe, version: 1.0.0.65, time stamp: 0x54bb18f3
Faulting module name: KERNELBASE.dll, version: 6.3.9600.17278, time stamp: 0x53eeb460
Exception code: 0xe0434352
Fault offset: 0x00012f71
Faulting process id: 0x1f0
Faulting application start time: 0x01d032ce40eb11c0
Faulting application path: C:\Users\Dave\AppData\Local\Apps\2.0\NYRN803G.0WT\PMA9B0T8.9Z9\stre..tion_0000000000000000_0001.0000_6fc848872dfedfbd\StreamLauncher.Wpf.exe
Faulting module path: C:\Windows\SYSTEM32\KERNELBASE.dll
Report Id: 8ec68285-9ec1-11e4-827b-201a06d47856
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-01-18T03:24:49.000000000Z" />
    <EventRecordID>9930</EventRecordID>
    <Channel>Application</Channel>
    <Computer>Jorgs-PC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>StreamLauncher.Wpf.exe</Data>
    <Data>1.0.0.65</Data>
    <Data>54bb18f3</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.3.9600.17278</Data>
    <Data>53eeb460</Data>
    <Data>e0434352</Data>
    <Data>00012f71</Data>
    <Data>1f0</Data>
    <Data>01d032ce40eb11c0</Data>
    <Data>C:\Users\Dave\AppData\Local\Apps\2.0\NYRN803G.0WT\PMA9B0T8.9Z9\stre..tion_0000000000000000_0001.0000_6fc848872dfedfbd\StreamLauncher.Wpf.exe</Data>
    <Data>C:\Windows\SYSTEM32\KERNELBASE.dll</Data>
    <Data>8ec68285-9ec1-11e4-827b-201a06d47856</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by lukehutton** [comment]
install vm and test

**Comment by lukehutton** [comment]
Found bug. Added logging and exception handling. `await _hockeyStreamRepository.GetLiveStreams(DateTime.Now);` must explicitly set date to format to `DateTime.Now.ToString("dd/MM/yyyy")`. Some environments setup with different locales.

**Comment by lukehutton** [comment]
Fixed. Added exception handling and changed async void so exception doesn't go unhandled. Fixed original bug which was passing in incorrect date. Added `CultureInfo.InvariantCulture` to `ToString` method on the date.
